In [2]:
import numpy as np
import pandas as pd
import glob
import split_dataset
import os
from collections import defaultdict

In [3]:
datasets = glob.glob("../learner-performance-prediction/data/*")
for dataset in datasets:
    path = "%s/preprocessed_data.csv" % dataset
    df = pd.read_csv(path, '\t')
    if 'Unnamed: 0' in df.columns:
        df = df.set_index('Unnamed: 0')
    print(df.columns)
    
    dataset_name = os.path.basename(dataset)
    print(dataset_name)
    
    df.columns = ['student', 'problem', 'timestamp', 'correct', 'skill']
    df.to_csv("datasets/gervetetal_%s.csv" % dataset_name, index=False)
    split_dataset.main("datasets/gervetetal_%s.csv" % dataset_name, "splits/gervetetal_%s.npy" % dataset_name)

Index(['user_id', 'item_id', 'timestamp', 'correct', 'skill_id'], dtype='object')
assistments15
[0.63993534 0.16003655 0.20002811]
[0.63993534 0.16003655 0.20002811]
[0.64000562 0.16003655 0.19995783]
[0.64000562 0.16003655 0.19995783]
[0.63993534 0.16003655 0.20002811]
Index(['user_id', 'item_id', 'timestamp', 'correct', 'skill_id'], dtype='object')
assistments17_single_attempt
[0.64051522 0.15983607 0.19964871]
[0.63992974 0.15983607 0.20023419]
[0.64051522 0.15983607 0.19964871]
[0.63992974 0.15983607 0.20023419]
[0.63992974 0.15983607 0.20023419]
Index(['user_id', 'item_id', 'timestamp', 'correct', 'skill_id'], dtype='object')
assistments17
[0.63992974 0.15983607 0.20023419]
[0.63992974 0.16042155 0.19964871]
[0.63992974 0.15983607 0.20023419]
[0.63934426 0.16042155 0.20023419]
[0.63992974 0.16042155 0.19964871]
Index(['user_id', 'item_id', 'timestamp', 'correct', 'skill_id'], dtype='object')
statics
[0.64184397 0.15957447 0.19858156]
[0.63829787 0.16312057 0.19858156]
[0.63829787 

In [5]:
datasets = glob.glob("../learner-performance-prediction/data/*")
for dataset in datasets:
    
    dataset_name = os.path.basename(dataset)
    print(dataset_name)
    
    df = pd.read_csv("datasets/gervetetal_%s.csv" % dataset_name)
    splits = np.load("splits/gervetetal_%s.npy" % dataset_name)
    
    train_ix = splits[0, :] == 2
    valid_ix = splits[0, :] == 1
    test_ix = splits[0, :] == 0
    
    train_df = df[train_ix]
    test_df = df[test_ix]
    
    train_items = set(train_df['problem'])
    test_items = set(test_df['problem'])
    
    print("Items in testing not in training: %d (total items: %d)" % 
          (len(test_items - train_items), len(set(df['problem']))))
    
    items_to_kc = defaultdict(set)
    for item, skill in zip(df['problem'], df['skill']):
        items_to_kc[item].add(skill)
    
    for item, kcs in items_to_kc.items():
        if len(kcs) > 1:
            print("Warning: Item %d has more than one KC" % item)

assistments15
Items in testing not in training: 0 (total items: 100)
assistments17_single_attempt
Items in testing not in training: 5 (total items: 3162)
assistments17
Items in testing not in training: 41 (total items: 3162)
statics
Items in testing not in training: 0 (total items: 1223)
assistments17_first_attempt
Items in testing not in training: 5 (total items: 3162)
assistments09
Items in testing not in training: 514 (total items: 17708)
algebra05
Items in testing not in training: 29287 (total items: 173113)
bridge_algebra06
Items in testing not in training: 8990 (total items: 129263)
spanish
Items in testing not in training: 0 (total items: 409)
assistments12
Items in testing not in training: 1262 (total items: 52850)
