In [2]:
import pandas as pd 
import numpy as np
import split_dataset

In [3]:
early_df = pd.read_csv("data/raw-datasets/csedm2020_fall/early.csv")
late_df = pd.read_csv("data/raw-datasets/csedm2020_fall/late.csv")
combined_df = pd.concat((early_df, late_df), axis=0, ignore_index=True)
combined_df

SubjectID  AssignmentID  \
0      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
1      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
2      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
3      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
4      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
...                                                  ...           ...   
23698  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23699  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23700  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23701  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23702  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   

       ProblemID  Attempts  CorrectEventually  Label  
0              1         1               True   True  
1              3         4               True   True  
2              5         3               True   True  
3             12         1               True   True  
4             13         6               True   True  
...          ...       ...                ...    ...  
23698         64         2               True   True  
23699         70         9               True  False  
23700         71         3               True   True  
23701        112         2               True   True  
23702        118         2               True   True  

[23703 rows x 6 columns]

In [4]:
students = sorted(set(combined_df['SubjectID']))
student_idx = dict(zip(students, range(len(students))))
problems = sorted(set(combined_df['ProblemID']))
problem_idx = dict(zip(problems, range(len(problems))))

print("Trials: %d, Students: %d, Problems: %d" % (combined_df.shape[0], len(students), len(problems)))

Trials: 23703, Students: 494, Problems: 50


In [9]:
output_df = pd.DataFrame({
    "student" : [student_idx[s] for s in combined_df['SubjectID']],
    "problem" : [problem_idx[p] for p in combined_df['ProblemID']],
    "correct" : combined_df['Label'].astype(int).tolist()
})
output_df['skill'] = output_df['problem']
output_df.to_csv("data/datasets/csedm2020.csv", index=False)
full_splits = split_dataset.main(output_df)
np.save("data/splits/csedm2020.npy", full_splits)

[0.63967611 0.15991903 0.20040486]
[0.63967611 0.15991903 0.20040486]
[0.63967611 0.15991903 0.20040486]
[0.63967611 0.16194332 0.19838057]
[0.63967611 0.15991903 0.20040486]


In [12]:
problem_df = pd.read_csv("embeddings/csedm2020_embeddings.csv")
problem_df['problem'] = [problem_idx[p] for p in problem_df['ProblemID']]
problem_df

0         1         2         3         4         5         6  \
0   0.031462 -0.018913  0.018152  0.000982 -0.029525  0.012743 -0.036470   
1   0.032123 -0.017724 -0.014483  0.002500 -0.017402  0.020252 -0.048269   
2   0.022520  0.021947 -0.003673 -0.010787 -0.002913  0.010147 -0.032347   
3   0.027796  0.013261 -0.002058 -0.015696 -0.031445  0.021920 -0.032814   
4   0.018218  0.014645  0.005776 -0.021426 -0.023497  0.009982 -0.042636   
5   0.005013  0.019903  0.012412 -0.028097 -0.003860  0.021661 -0.026745   
6   0.014848 -0.000117  0.019562 -0.018243 -0.029957  0.007006 -0.019249   
7   0.007449  0.000369  0.000423 -0.013949 -0.028146  0.005475 -0.031530   
8   0.002180 -0.007484  0.034440 -0.036691 -0.003381  0.016164 -0.033745   
9   0.004855 -0.011747  0.022308 -0.007025 -0.039022 -0.007533 -0.037360   
10  0.000087 -0.005410  0.003422 -0.000270 -0.024956  0.002589 -0.047442   
11  0.015079  0.003502  0.013888  0.017728 -0.022973  0.010369 -0.020471   
12  0.009800  0.003544  0.009673  0.010586 -0.025092  0.019131 -0.026810   
13  0.011506  0.013399  0.024333 -0.011840 -0.016190  0.011867 -0.018995   
14  0.028319  0.005522  0.020971  0.018268 -0.015786  0.002768 -0.031021   
15  0.022995  0.010476  0.003311  0.002179 -0.010646  0.017558 -0.014501   
16  0.021449  0.015734 -0.027606 -0.004208 -0.027891  0.010468 -0.025297   
17  0.017328  0.005246  0.014353 -0.006200 -0.001473  0.011285 -0.027240   
18  0.027179 -0.008129  0.013039 -0.004750 -0.017553 -0.001830 -0.027694   
19  0.013336  0.026578  0.003668  0.011993 -0.038404  0.006324 -0.014338   
20  0.020500 -0.000768 -0.004262  0.005769 -0.020204  0.000029 -0.024988   
21  0.017064  0.032828  0.005082  0.005801 -0.026799  0.002124 -0.007211   
22  0.015447 -0.002769 -0.005019  0.015886 -0.021634  0.016818 -0.022459   
23  0.004191  0.032619  0.018397 -0.009046 -0.025805  0.044091 -0.005750   
24  0.010680  0.021250  0.000769 -0.006631 -0.012788  0.011641 -0.012465   
25  0.020901  0.005955  0.003576 -0.009860 -0.021946  0.012629 -0.010464   
26  0.019073  0.015542  0.009336 -0.007082 -0.041014  0.011639 -0.017887   
27  0.002054  0.015066  0.015500 -0.018050 -0.024979  0.007560 -0.031082   
28  0.014122  0.010689  0.022321  0.004382 -0.008676 -0.017865 -0.013200   
29  0.006845  0.011463 -0.008718 -0.006217 -0.047610  0.021521 -0.020088   
30  0.010831  0.015441  0.023585 -0.000893 -0.038712  0.006544 -0.021279   
31  0.001236  0.002903 -0.014464 -0.002048 -0.031629  0.014938 -0.019754   
32  0.013741  0.008439 -0.004772 -0.013610 -0.032686  0.000762 -0.034334   
33  0.002408  0.012730 -0.002299  0.005144 -0.026759  0.001814 -0.020909   
34  0.015550 -0.005874  0.005371 -0.005752 -0.032636  0.006487 -0.034093   
35  0.005823  0.016537 -0.000744  0.008820 -0.048898  0.004804 -0.017102   
36  0.007415  0.004525 -0.003037  0.002777 -0.017922  0.032122 -0.011902   
37  0.000657 -0.006710 -0.001225 -0.019514 -0.046537  0.000445 -0.016830   
38 -0.003433  0.027267  0.017220 -0.004846 -0.007653  0.008159 -0.002869   
39  0.005982  0.011896 -0.017911 -0.012703 -0.029282  0.015543 -0.029148   
40  0.014308  0.006280  0.009058 -0.007324 -0.035879  0.013424 -0.016620   
41  0.007438 -0.013015 -0.002045  0.001454 -0.020780  0.037142 -0.035080   
42  0.001818 -0.009431 -0.010901 -0.001213 -0.010853  0.031409 -0.022455   
43 -0.005859  0.019442  0.023183 -0.007113 -0.021292  0.005454 -0.004230   
44 -0.007776 -0.012668 -0.020768 -0.021954 -0.030566  0.006988 -0.042102   
45 -0.011173 -0.012960 -0.008029 -0.023366 -0.033785  0.015065 -0.024928   
46  0.011076  0.019943 -0.013506  0.013238 -0.027465  0.016965 -0.027231   
47  0.015447  0.009250  0.032387  0.005267 -0.027473  0.013282 -0.018935   
48  0.001244 -0.002441 -0.009913 -0.013974  0.000530  0.016920 -0.031381   
49  0.005787  0.001230  0.006385 -0.006903 -0.031270  0.032679 -0.034005   

           7         8         9  ...      1529      1530      1531      1532  \
0  -0.013199 -0.014320 -0.025319  ... -0.024932 -0.02

In [13]:
problem_df.to_csv("embeddings/csedm2020_embeddings.csv", index=False)

# Extract correct solutions to the problems

In [15]:
code_states_df = pd.read_csv("data/raw-datasets/csedm2020_fall/Data/CodeStates/CodeStates.csv").set_index('CodeStateID')
code_states_df

Code
CodeStateID                                                                                          
e03c3817ba234c667140a5281960bfc79238ef075b48c76...  public int caughtSpeeding(int speed, boolean i...
cdfe99579672f04db808aa7343826bf3c71751dfba129d5...  public int caughtSpeeding(int speed, boolean i...
511eeec6958a4d834c7419dc55b4831655b13aa6d343acc...  public int caughtSpeeding(int speed, boolean i...
4c09d5ddc005e6104a8f58f76ee1020eb0adc109b13cb01...  public int caughtSpeeding(int speed, boolean i...
71514451fe4c010093a06f9f58eced6ae9de98a13edae7f...  public int caughtSpeeding(int speed, boolean i...
...                                                                                               ...
26f6c69d9d1c5e04a21ea25119f8731efabb61b19465399...  public String[] fizzBuzz(int start, int end)\r...
e35dfdbf92f649e422e9bb09eeb5c26f22ab35974f18970...  public boolean twoTwo(int[] nums)\r\n{\r\n    ...
0fe639c903e66b392e84bb09b44b8fbab6bffa0e9a8ddf7...  public boolean canBalance(int[] nums)\r\n{\r\n...
3f38721fce5c023a1b14052db91722cb1d3738fde0e160c...  public int[] seriesUp(int n)\r\n{\r\n    int[]...
5edb15c9560480acbf8720dcaf33650f4f92ed79f1c73c1...  public int[] shiftLeft(int[] nums)\r\n{\r\n   ...

[125578 rows x 1 columns]

In [27]:
raw_df = pd.read_csv('data/raw-datasets/csedm2020_fall/Data/MainTable.csv')
ix_correct = raw_df['Score'] == 1
corr_raw_df = raw_df[ix_correct].copy()
corr_raw_df['code'] = code_states_df.loc[corr_raw_df['CodeStateID'], 'Code'].tolist()

In [28]:
corr_raw_df

SubjectID  \
0       00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...   
9       00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...   
17      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...   
19      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...   
68      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...   
...                                                   ...   
360149  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...   
360154  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...   
360158  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...   
360166  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...   
360174  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...   

              ToolInstances      ServerTimestamp  ServerTimezone CourseID  \
0       Java 8; CodeWorkout  2019-09-27T12:43:31               0     CS 1   
9       Java 8; CodeWorkout  2019-09-27T12:53:37               0     CS 1   
17      Java 8; CodeWorkout  2019-09-27T12:36:22               0     CS 1   
19      Java 8; CodeWorkout  2019-09-27T12:56:42               0     CS 1   
68      Java 8; CodeWorkout  2019-09-27T11:36:39               0     CS 1   
...                     ...                  ...             ...      ...   
360149  Java 8; CodeWorkout  2019-12-02T15:20:22               0     CS 1   
360154  Java 8; CodeWorkout  2019-12-02T15:25:42               0     CS 1   
360158  Java 8; CodeWorkout  2019-12-02T15:28:51               0     CS 1   
360166  Java 8; CodeWorkout  2019-12-02T13:54:24               0     CS 1   
360174  Java 8; CodeWorkout  2019-12-02T14:10:56               0     CS 1   

        AssignmentID  ProblemID  \
0                439          1   
9                439          3   
17               439          5   
19               439         12   
68               439         13   
...              ...        ...   
360149           502         71   
360154           502        112   
360158           502        118   
360166           502         45   
360174           502         48   

                                              CodeStateID  \
0       5c3b1a18d738139379a040695b382bb8a44f0be2302fa7...   
9       7451e25234b583a1790f273fe2a3a07843369046e2b61f...   
17      97128da6b09ee0c097ff082725e53a1e22355ea5323a4f...   
19      98cbe22f5a9cb327e6bc6c08b49332de976e7959546155...   
68      d15f5c38e6b57bd337c9d32153d0f0cab6611fd69f6a3e...   
...                                                   ...   
360149  8b5bb54b63103c4c45ee58aa6f8bbd0c6890fba1d82153...   
360154  add860149e169c4e0ef359e8523a475bff1cb35185d799...   
360158  38e11aa1c182ae86953bcf1b435fd1a7e9decdb7434aee...   
360166  48f0619aefa91f22f32dd938c26594160079280eb50ed5...   
360174  dc69e0187b8ab8b4489196195578c86c561dc11938cbc8...   

        IsEventOrderingConsistent    EventType  Score Compile.Result  \
0                            True  Run.Program    1.0            NaN   
9                            True  Run.Program    1.0            NaN   
17                           True  Run.Program    1.0            NaN   
19                           True  Run.Program    1.0            NaN   
68                           True  Run.Program    1.0            NaN   
...                           ...          ...    ...            ...   
360149                       True  Run.Program    1.0            NaN   
360154                       True  Run.Program    1.0            NaN   
360158                       True  Run.Program    1.0            NaN   
360166                       True  Run.Program    1.0            NaN   
360174                       True  Run.Program    1.0            NaN   

       CompileMessageType CompileMessageData  EventID   Order  ParentEventID  \
0                     NaN                NaN    11161   11161            NaN   
9                     NaN                NaN    11170   11170            NaN   
17                    NaN                NaN    11139   11139            NaN   
19                    NaN                NaN    111

In [31]:
gdf = corr_raw_df.groupby('ProblemID')['code'].agg(lambda codes: np.random.choice(codes)).reset_index()
gdf['problem'] = [problem_idx[p] for p in gdf['ProblemID']]
gdf

ProblemID                                               code  problem
0           1  public int sortaSum(int a, int b)\r\n{\r\n    ...        0
1           3  public boolean in1To10(int n, boolean outsideM...        1
2           5  public boolean answerCell(boolean isMorning, b...        2
3          12  public boolean squirrelPlay(int temp, boolean ...        3
4          13  public int caughtSpeeding(int speed, boolean i...        4
5          17  public int redTicket(int a, int b, int c)\r\n{...        5
6          20  public int loneSum(int a, int b, int c)\r\n{\r...        6
7          21  public int luckySum(int a, int b, int c)\r\n{\...        7
8          22  public int noTeenSum(int a, int b, int c)\r\n{...        8
9          24  public int blackjack(int a, int b)\r\n{\r\n   ...        9
10         25  public boolean evenlySpaced(int a, int b, int ...       10
11         28  public String atFirst(String str)\r\n{\r\n    ...       11
12         31  public String repeatEnd(String str, int n)\r\n...       12
13         32  public String plusOut(String str, String word)...       13
14         33  public String mixString(String a, String b)\r\...       14
15         34  public String zipZap(String str)\r\n{\r\n    i...       15
16         36  public int countCode(String str)\r\n{\r\n    i...       16
17         37  public boolean endOther(String a, String b)\r\...       17
18         38  public boolean xyzThere(String str)\r\n{\r\n  ...       18
19         39  public boolean xyBalance(String str)\r\n{\r\n ...       19
20         40  public String getSandwich(String str)\r\n{\r\n...       20
21         41  public int sum3(int[] nums)\r\n{\r\n    return...       21
22         43  public int[] frontPiece(int[] nums)\r\n{\r\n  ...       22
23         44  public int countEvens(int[] nums)\r\n{\r\n\t i...       23
24         45  public int sum67(int[] nums)\r\n{\r\n    int x...       24
25         46  public boolean isEverywhere(int[] nums, int va...       25
26         48  public int[] withoutTen(int[] nums)\r\n{\r\n  ...       26
27         49  public int sum13(int[] nums)\r\n{\r\n    int s...       27
28         51  public int[] tenRun(int[] nums)\r\n{\r\n    fo...       28
29         56  public int centeredAverage(int[] nums)\r\n{\r\...       29
30         57  public int[] fizzArray(int n)\r\n{\r\n    int[...       30
31         64  public String[] fizzBuzz(int start, int end)\r...       31
32         67  public boolean has77(int[] nums)\r\n{\r\n    f...       32
33         70  public boolean twoTwo(int[] nums) {\r\n    if(...       33
34         71  public boolean canBalance(int[] nums)\r\n{\r\n...       34
35        100  public int roundSum(int a, int b, int c)\r\n{\...       35
36        101  public int makeChocolate(int small, int big, i...       36
37        102  public String without2(String str) \r\n{\r\n  ...       37
38        104  public int[] zeroMax(int[] nums)\r\n{\r\n    i...       38
39        106  public boolean sameEnds(int[] nums, int n)\r\n...       39
40        107  public int countClumps(int[] nums)\r\n{\r\n   ...       40
41        108  public int[] fix45(int[] nums)\r\n{\r\n   int ...       41
42        112  public int[] seriesUp(int n)\r\n{\r\n    int x...       42
43        118  public int[] shiftLeft(int[] nums)\r\n{\r\n   ...       43
44        128  public boolean bobThere(String str)\r\n{\r\n  ...       44
45        232  public String alarmClock(int day, boolean vaca...       45
46        233  public boolean love6(int a, int b)\r\n{\r\n   ...       46
47        234  public boolean cigarParty(int cigars, boolean ...       47
48        235  public int dateFashion(int you, int date)\r\n{...       48
49        236  public int greenTicket(int a, int b, int c)\r\...       49

In [32]:
gdf.to_csv('tmp/csedm2020_solutions.csv', index=False)