In [13]:
import pandas as pd 
import numpy as np
import split_dataset

In [3]:
early_df = pd.read_csv("../../Downloads/All/early.csv")
late_df = pd.read_csv("../../Downloads/All/late.csv")
combined_df = pd.concat((early_df, late_df), axis=0, ignore_index=True)
combined_df

SubjectID  AssignmentID  \
0      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
1      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
2      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
3      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
4      00358c94503a8d9e6869efc6e5cdb0e1c8e9eb39b1fd46...           439   
...                                                  ...           ...   
23698  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23699  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23700  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23701  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   
23702  ffc3b91c3744d275e99f49e105f016732d694a76314d8c...           502   

       ProblemID  Attempts  CorrectEventually  Label  
0              1         1               True   True  
1              3         4               True   True  
2              5         3               True   True  
3             12         1               True   True  
4             13         6               True   True  
...          ...       ...                ...    ...  
23698         64         2               True   True  
23699         70         9               True  False  
23700         71         3               True   True  
23701        112         2               True   True  
23702        118         2               True   True  

[23703 rows x 6 columns]

In [9]:
students = sorted(set(combined_df['SubjectID']))
student_idx = dict(zip(students, range(len(students))))
problems = sorted(set(combined_df['ProblemID']))
problem_idx = dict(zip(problems, range(len(problems))))

print("Trials: %d, Students: %d, Problems: %d" % (combined_df.shape[0], len(students), len(problems)))

Trials: 23703, Students: 494, Problems: 50


In [15]:
output_df = pd.DataFrame({
    "student" : [student_idx[s] for s in combined_df['SubjectID']],
    "problem" : [problem_idx[p] for p in combined_df['ProblemID']],
    "correct" : combined_df['Label'].astype(int).tolist()
})
output_df.to_csv("tmp/csedm2020.csv", index=False)
full_splits = split_dataset.main(output_df)
np.save("tmp/splits_csedm2020.npy", full_splits)

[0.63967611 0.15991903 0.20040486]
[0.63967611 0.15991903 0.20040486]
[0.63967611 0.15991903 0.20040486]
[0.63967611 0.16194332 0.19838057]
[0.63967611 0.15991903 0.20040486]


In [16]:
problem_df = pd.read_csv("tmp/csedm2020_embeddings.csv")
assert len(set(combined_df['ProblemID']) - set(problem_df['ProblemID'])) == 0